### PR TITLE
Forward port latest pipework script

### PR DESCRIPTION
**Pull request by swettk**
Needed to support latest Ubuntu LTS release.

### CODE REVIEW

**Comment by swettk** [comment]
Any time to look?

**Comment by swettk** [comment]
@fpletz @globin  Any chance to look at this?

**Comment by fgrehm** [comment]
hey guys, I've just added @swettk as a collaborator and gave him the 👍 on moving forward with this, but since I don't use the plugin anymore it would be nice to have another set of eyes on it before merging it. would any of you be able to review / test it?

/cc @ccope

**Comment by ccope** [comment]
The command line arguments seem to be backwards compatible. This script seems pretty self-contained, so I wouldn't mind just merging it.

**Comment by swettk** [comment]
Thanks!

**Pull request merged**
