### PR TITLE
[WIP] Private networks

### PR DESCRIPTION
**Pull request by fgrehm**
I had a need for private networks last week and this is my first stab at implementing GH-120

### TODO

- [x] Integrate pipework into the plugin
- [ ] ~~Remove docker specifics from the script~~ not worth the trouble and will make things harder when bringing in upstream changes.
- [x] Make it work with a single ip range (`192.168.1.X`)
- [x] Clean up when shutting down container (use `brctl show brX` to check if in use and `ip link delete brX` to clean up)
- [ ] ~~Make it work for any ip range / create multiple bridges~~ Decided to keep things simple and will require the bridge name to be set
- [ ] Validate if bridge name is set
- [x] Create bridge only if it is not up
- [x] Make sure it works when bringing up containers in parallel
- [x] Whitelist sudo for private network script execution
- [x] Improve logging / provide information when networking is being configured / deconfigured

### CODE REVIEW

**Comment by fgrehm** [comment]
An experimental support for this is available at the `next` branch and will be released with 1.1.0 (expected at some point in jan / feb)

Docs will come along with the release but for the brave souls willing to build the plugin from sources and give it a spin this is what you'll need to set from the Vagrantfile:

```ruby
  config.vm.network "private_network", ip: "CONTAINER_IP", lxc__bridge_name: 'BRIDGE_NAME'
```

`lxc__bridge_name` is currently required. Support for using a "dynamic name" will be added post 1.1.0

**Comment by Ramblurr** [comment]
If using virbr0 provided by libvirtd, as outlined in the [fedora wiki entry](https://github.com/fgrehm/vagrant-lxc/wiki/Usage-on-fedora-hosts#add-snippet-to-vagrantfile-to-override-default-in-fgrehms-base-boxes), does the lxc__bridge_name field need to be set to virbro0?

**Comment by fgrehm** [comment]
Yes, right now the config has to be set at all times.

**Comment by moos3** [comment]
I noticed they can ping reach other but can't talk to each other on ports. I have verified my firewall settings on my multiple node Vagrant file. Thoughts or Ideas? Seems to be related to this.

**Pull request closed without merging**
