### PR TITLE
Getting vagrant-lxc work with system bridge for private network

### PR DESCRIPTION
**Pull request by podarok**
Fixing https://github.com/fgrehm/vagrant-lxc/issues/353 issue

With this patch system bridge can be used like a charm out of the box

### CODE REVIEW

**Comment by fgrehm** [comment]
Thanks!

This is a good start but I'd prefer a patch that skips bridge removal in case it was not created by vagrant-lxc.... Lemme think about this a bit more

**Comment by podarok** [comment]
@fgrehm I have updated a place where remove_bridge invokes. So now routine should work without even calling remove_bridge when there is a system reserved bridge name
Needs test

**Comment by stucki** [comment]
There's a small bug in your https://github.com/podarok/vagrant-lxc/commit/65c7f956e7ae352317e1a5b7cb50810b909c2752: The variable name is "bridge" not "bridge_name".

**Comment by stucki** [comment]
See also #380

**Comment by fgrehm** [comment]
Sorry for the long silence but as per GH-375 I'm looking for help to maintain this plugin and for now I'm holding back from bringing in new changes =/

If you are interested on maintaining the project and keep things moving please shoot me an email or drop a message on GH-375 so I can arrange things.

Cheers :beers:

**Comment by stucki** [comment]
I've created a new PR which includes both changes from this one, but also includes the variable name fix, see #383.

**Comment by fpletz** [comment]
Closing this in favor of #383.

Thanks @podarok! Your commits are included in the new PR.

**Pull request closed without merging**
